spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: yousef
    password: showman
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        show_sql: ture
    database: postgresql
