spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lms
    username: postgres
    password: showman
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: lmsprojectfcai@gmail.com
    password: otlpjjusteoistae
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true